name: Red Hat JBoss Fuse Service Works
abbreviated_name: JBoss Fuse Service Works
tagline: An open source service design, development and integration platform that speeds up cloud integration.
forum_url: https://community.jboss.org/en/fsw 
documentation_url: https://access.redhat.com/site/documentation/Red_Hat_JBoss_Fuse_Service_Works/

