name: Red Hat JBoss Fuse Service Works
abbreviated_name: JBoss Fuse Service Works
tagline: An open source service design, development and integration platform that speeds up cloud integration.
forum_url: https://community.jboss.org/en/fsw 
guide_base_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6-Beta/
guides:
  Administration_and_Configuration_Guide:
  API_Documentation:
  Development_Guide_Volume_1_SwitchYard:
    name: "Development Guide Volume 1: SwitchYard"
  Development_Guide_Volume_2_Smooks:
    name: "Development Guide Volume 2: Smooks"
  Development_Guide_Volume_3_Governance:
    name: "Development Guide Volume 3: Governance"
  Development_Guide_Volume_4_BPEL:
    name: "Development Guide Volume 4: BPEL"
  Getting_Started_Guide:
  Installation_Guide:
  Release_Notes:
  Security_Guide:
  User_Guide:

