name: Red Hat JBoss Operations Network
abbreviated_name: JBoss Operations Network
product_logo: portal.png
current_version: 3.3.0.GA
documentation_path: Red_Hat_JBoss_Operations_Network
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Operations_Network/3.3/html/3.3_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Operations_Network/3.3/html-single/3.3_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Operations_Network/3.3/epub/3.3_Release_Notes/Red_Hat_JBoss_Operations_Network-3.3-3.3_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Operations_Network/3.3/pdf/3.3_Release_Notes/Red_Hat_JBoss_Operations_Network-3.3-3.3_Release_Notes-en-US.pdf
  Installation_Guide:
  Admin_and_Config:
    name: 'Configuring JON Servers and Agents'
  Users_Guide:
    name: 'USING JBOSS OPERATIONS NETWORK FOR MONITORING, DEPLOYING, AND MANAGING RESOURCES'
  Complete_Resource_Reference:
    name: 'Development - Complete Resource Reference'
  Writing_Custom_Plug-ins:
    name: 'Development - Writing Custom Plug-ins'
  Rest_API:
    name: 'Development - REST API'
  Remote_API:
    name: 'Development - Remote API'
  Writing_JON_Command-Line_Scripts:
    name: 'Development - Writing JON Command-Line Scripts'
description: 'A SINGLE POINT OF CONTROL TO DEPLOY, MANAGE, AND MONITOR YOUR RED HAT JBOSS ENTERPRISE MIDDLEWARE PRODUCTS, APPLICATIONS, AND SERVICES'
downloads:
skip_maven_instructions: true
other_product: true
