name: Red Hat JBoss Portal
abbreviated_name: JBoss Portal
forum_url: https://community.jboss.org/en/jbossjpp
current_version: 6.1.0.GA
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  User_Guide:

