name: Red Hat JBoss Portal
abbreviated_name: JBoss Portal
forum_url: https://community.jboss.org/en/jbossjpp
documentation_url: https://access.redhat.com/site/documentation/Red_Hat_JBoss_Portal/
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  User_Guide:

