version: '2'
services:

  acceptance_tests:
   build: ../
   volumes:
    - ../../:/home/testing/developers.redhat.com
   environment:
    - ghprbActualCommit
    - github_status_api_token
    - SELENIUM_HOST=http://selhub:4444/wd/hub
    - PARALLEL_TEST
    - CUCUMBER_TAGS
    - RHD_JS_DRIVER
    - RHD_TEST_PROFILE

  selhub:
    image: selenium/hub
    restart: always
    expose:
      - "4444"
    ports:
      - "4444"
    privileged: true
    environment:
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000

  docker_chrome:
     image: selenium/node-chrome-debug:2.53.0
     volumes:
      - /dev/shm:/dev/shm
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"

  docker_firefox:
     image: selenium/node-firefox-debug:2.53.0
     volumes:
      - /dev/shm:/dev/shm
     environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
     depends_on:
      - selhub
     ports:
      - "5900"