name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
forum_url: https://community.jboss.org/en/datavirt
documentation_url: https://access.redhat.com/site/documentation/Red_Hat_JBoss_Data_Virtualization
current_version: 6.0.0.Beta
guide_base_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6-Beta
guides:
  Development_Guide_Reference_Material:
    name: "Development Guide: Reference Material"
  Development_Guide_Server_Development:
    name: "Development Guide: Server Development"
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  Release_Notes:

