name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
forum_url: https://community.jboss.org/en/datavirt
documentation_url: https://access.redhat.com/site/documentation/Red_Hat_JBoss_Data_Virtualization/

