name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
forum_url: https://community.jboss.org/en/datavirt
current_version: 6.0.0.Beta
documentation_minor_version: 6-Beta
guides:
  Development_Guide_Reference_Material:
    name: "Development Guide: Reference Material"
  Development_Guide_Server_Development:
    name: "Development Guide: Server Development"
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  Release_Notes:
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6-Beta/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6-Beta/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6-Beta/pdf/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6-Beta-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6-Beta/epub/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6-Beta-Release_Notes-en-US.epub

