name: Red Hat Enterprise Linux OpenStack Platform
abbreviated_name: RHEL OpenStack Platform
product_logo: portal.png
current_version: 6.0.0.GA
customer_portal_download_url: https://access.redhat.com/products/red-hat-enterprise-linux-openstack-platform/get-started
documentation_path: Red_Hat_Enterprise_Linux_OpenStack_Platform
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
index:
  desc: |
    Red Hat Enterprise Linux OpenStack Platform delivers an integrated foundation to create, deploy, and scale a secure and reliable public or private OpenStack cloud.
guides:
  Top_New_Features:
    name: "Red Hat Enterprise Linux OpenStack Platform 6 - Top New Features"
    formats:
      html:
        url: https://access.redhat.com/articles/1274673
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Release_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/epub/Release_Notes/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Release_Notes/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Release_Notes-en-US.pdf
  Technical_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Technical_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Technical_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/epub/Technical_Notes/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Technical_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Technical_Notes/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Technical_Notes-en-US.pdf
  Package_Manifest:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Package_Manifest/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Package_Manifest/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/epub/Package_Manifest/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Package_Manifest-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Package_Manifest/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Package_Manifest-en-US.pdf
  Single-Node_Deployment:
    name: "Evaluating OpenStack: Single-Node Deployment"
    formats:  
      html:
        url: https://access.redhat.com/articles/1127153
  Simple_Deployment:
    name: "Evaluating OpenStack: Simple Networking"
    formats:  
      html:
        url: https://access.redhat.com/node/1146173/
  Deploying_OpenStack_Learning_Environments:
    name: "Deploying OpenStack: Learning Environments (Manual Setup)"
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Deploying_OpenStack_Learning_Environments/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Deploying_OpenStack_Learning_Environments/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/epub/Deploying_OpenStack_Learning_Environments/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Deploying_OpenStack_Learning_Environments-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Deploying_OpenStack_Learning_Environments/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Deploying_OpenStack_Learning_Environments-en-US.pdf
  Administration_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Administration_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Administration_Guide/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Administration_Guide/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Administration_Guide-en-US.pdf
  Launch_an_Instance:
    formats:
      html: 
        url: https://access.redhat.com/articles/1249993
  Command-Line_Interface_Reference:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Command-Line_Interface_Reference_Guide/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Command-Line_Interface_Reference_Guide/index.html
      pdf:
        url: nhttps://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Command-Line_Interface_Reference_Guide/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Command-Line_Interface_Reference_Guide-en-US.pdf
  Component_Overview:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Component_Overview/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Component_Overview/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/epub/Component_Overview/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Component_Overview-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Component_Overview/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Component_Overview-en-US.pdf
  Configuration_Reference:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Configuration_Reference_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html-single/Configuration_Reference_Guide/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/pdf/Configuration_Reference_Guide/Red_Hat_Enterprise_Linux_OpenStack_Platform-6-Configuration_Reference_Guide-en-US.pdf
description: 'BUILD PUBLIC AND PRIVATE CLOUDS ON A SECURE, SCALABLE FOUNDATION'
downloads:
skip_maven_instructions: true
other_product: true
