name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
tagline: Single Development Tool, Tailored for Extreme Productivity
documentation_url: https://access.redhat.com/site/documentation/Red_Hat_JBoss_Developer_Studio/
forum_url: https://community.jboss.org/en/jbossdevstudio 

