name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
tagline: Single Development Tool, Tailored for Extreme Productivity
forum_url: https://community.jboss.org/en/jbossdevstudio 
current_version: 7.1.0.GA
guides:
  CDI_Tools_Reference_Guide:
  Getting_Started_Guide:
  Hibernate_Tools_Reference_Guide:
  Installation_Guide:
  JBoss_Portlet_Tools_User_Guide:
  JBoss_RESTful_Web_Services_User_Guide:
  JBoss_SOAP_Web_Services_User_Guide:
  JMX_Tools_Reference_Guide:
  JSF_Tools_Reference_Guide:
  JSF_Tools_Tutorial:
  Maven_Tools_Reference_Guide:
  Migration_Guide:
  Release_Notes_7.1.0:
  Seam_Developer_Tools_Reference_Guide:
  Seam_Tools_Tutorial:
  User_Guide:
  Visual_Web_Tools_Reference_Guide:
downloads:
  7.1.0.GA:
    release_date: 2013-12-16
    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
    assets:
      jar-universal:
        size: 613mb
        name: Jar (Universal Binary with EAP)
      jar-standalone:
        size: 487mb
        name: Jar (Standalone Universal Binary)
      zip-central:
        size: 410mb
        name: Zip (Standalone Universal Binary)
      zip-update:
        size: 719mb
        name: Zip (Standalone Universal Binary)
      source:
        size: 6mb
  7.0.0.GA:
    release_date: 2013-07-23
    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
    assets:
      jar-universal:
        size: 591mb
        name: Jar (Universal Binary with EAP)
      jar-standalone:
        size: 481mb
        name: Jar (Standalone Universal Binary)
      zip-update:
        size: 697mb
        name: Zip (Standalone Universal Binary)
      source:
        size: 6mb
  6.0.1.GA:
    release_date: 2013-04-04
    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
    assets:
      jar-universal:
        size: 566mb
        name: Jar (Universal Binary with EAP)
      jar-standalone:
        size: 455mb
        name: Jar (Standalone Universal Binary)
      source:
        size: 111mb
  6.0.0.GA:
    release_date: 2012-12-07
    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
    assets:
      jar-universal:
        size: 564mb
        name: Jar (Universal Binary with EAP)
      jar-standalone:
        size: 454mb
        name: Jar (Standalone Universal Binary)
      source:
        size: 3mb
  5.0.0.GA:
    release_date: 2012-06-21
    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
    assets:
      jar-universal:
        size: 495mb
        name: Jar (Universal Binary with EAP)
      jar-standalone:
        size: 385mb
        name: Jar (Standalone Universal Binary)
      source:
        size: 111mb

