name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
tagline: Single Development Tool, Tailored for Extreme Productivity
forum_url: https://community.jboss.org/en/jbossdevstudio 
current_version: 7.1.0.GA
guides:
  CDI_Tools_Reference_Guide:
  Getting_Started_Guide:
  Hibernate_Tools_Reference_Guide:
  Installation_Guide:
  JBoss_Portlet_Tools_User_Guide:
  JBoss_RESTful_Web_Services_User_Guide:
  JBoss_SOAP_Web_Services_User_Guide:
  JMX_Tools_Reference_Guide:
  JSF_Tools_Reference_Guide:
  JSF_Tools_Tutorial:
  Maven_Tools_Reference_Guide:
  Migration_Guide:
  Release_Notes_7.1.0:
  Seam_Developer_Tools_Reference_Guide:
  Seam_Tools_Tutorial:
  User_Guide:
  Visual_Web_Tools_Reference_Guide:

