kramdown:
  :input: 'QuickStartParser'
download_manager_file_base_url: http://www.jboss.org/download-manager/f
product_documentation_base_url: https://access.redhat.com/site/documentation/en-US
product_forum_base_url: https://community.jboss.org/en/
vimeo_client_id: 2589d6592dfd44bfec54f22edf766aedaf0fd5d7
vimeo_access_token: 1ad6583e71e183c3075a88d46ebb0675
profiles:
  development:
    dcp_base_url: https://dcp-jbossorgdev.rhcloud.com/
  staging:
    base_url: http://www-stg.jboss.org
    dcp_base_url: https://dcp-jbossorgdev.rhcloud.com/
    deploy:
      host: github_pages
      branch: www-staging
      repository: deployment
  production:
    dcp_base_url:
  wes:
    site_url: http://test.com:4242
    dcp_base_url:

