kramdown:
  :input: 'QuickStartParser'
download_manager_file_base_url: http://www-eng.jboss.org/download-manager/file
product_documentation_base_url: https://access.redhat.com/site/documentation/en-US
product_forum_base_url: https://community.jboss.org/en/
vimeo_client_id: 2589d6592dfd44bfec54f22edf766aedaf0fd5d7
vimeo_access_token: 1ad6583e71e183c3075a88d46ebb0675
register_url: https://community.jboss.org/register.jspa
profiles:
  development:
    dcp_base_url: http://dcp-jbossorgdev.rhcloud.com
  staging:
    base_url: http://www-stg.jboss.org
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    deploy:
      host: www@filemgmt.jboss.org
      path: /stg_htdocs/www-stg
      uncommitted: true   
  filemgmt:
    base_url: http://www-stg2.jboss.org/
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
  production:
    dcp_base_url:
  wes:
    site_url: http://test.com:4242
    dcp_base_url:

