name: Red Hat Software Collections
abbreviated_name: Software Collections
product_logo: portal.png
current_version: 1.1.0.GA
documentation_path: Red_Hat_Software_Collections
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html/1.1_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html-single/1.1_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/epub/1.1_Release_Notes/Red_Hat_Software_Collections-1-1.1_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/pdf/1.1_Release_Notes/Red_Hat_Software_Collections-1-1.1_Release_Notes-en-US.pdf
  Installation_and_Usage: 
    formats:
      html: 
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html/1.1_Release_Notes/chap-Installation_and_Usage.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html-single/1.1_Release_Notes/index.html#chap-Installation_and_Usage
  Packaging_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html/Packaging_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html-single/Packaging_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/epub/Packaging_Guide/Red_Hat_Software_Collections-1-Packaging_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/pdf/Packaging_Guide/Red_Hat_Software_Collections-1-Packaging_Guide-en-US.pdf
description: Hello World
downloads:
skip_maven_instructions: true
other_product: true
