name: Red Hat Software Collections
abbreviated_name: Software Collections
product_logo: portal.png
current_version: 2.0.GA
documentation_path: Red_Hat_Software_Collections
customer_portal_download_url: https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.1/x86_64/product-downloads
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
description: The latest development technologies for Red Hat Enterprise Linux
index:
  desc: |
    With a separate life cycle from Red Hat Enterprise Linux and a yearly release cadence, Red Hat Software Collections delivers the latest stable technologies such as: Python, PHP, Ruby, Node.js, MariaDB, MongoDB, PostgreSQL, Nginx, and much more.  
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html/2.0_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html-single/2.0_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/epub/2.0_Release_Notes/Red_Hat_Software_Collections-2-2.0_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/pdf/2.0_Release_Notes/Red_Hat_Software_Collections-2-2.0_Release_Notes-en-US.pdf
  Installation_and_Usage: 
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html/2.0_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html-single/2.0_Release_Notes/index.html  Packaging_Guide:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html/Packaging_Guide/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html-single/Packaging_Guide/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/epub/Packaging_Guide/Red_Hat_Software_Collections-2-Packaging_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/pdf/Packaging_Guide/Red_Hat_Software_Collections-2-Packaging_Guide-en-US.pdf
description: Hello World
downloads:
skip_maven_instructions: true
other_product: true
