name: Red Hat JBoss Web Server
abbreviated_name: JBoss Web Server
documentation_url: https://access.redhat.com/site/documentation/JBoss_Enterprise_Web_Server
current_version: 2.0.0.GA
guides:
  Release_Notes:
  Hibernate_Core_Guide:
  HTTP_Connectors_Load_Balancing_Guide:
  Installation_Guide:

