name: Red Hat JBoss Fuse
abbreviated_name: JBoss Fuse
tagline: A small footprint, flexible, open source ESB
downloads:
  6.0.0.GA:
    release_date: 2013-04-10
    description: Our small footprint Enterprise Service Bus (ESB) that can be moved into production with a Red Hat subscription.
    assets:
      zip-full:
        size: 568mb
        name: Zip (Full Install)
      zip-medium:
        size: 202mb
        name: Zip (Medium Install)
      ide-macosx:
        size:
        name: Fuse IDE (MacOS X)
      ide-win32:
        size:
        name: Fuse IDE (Windows 32bit)
      ide-win32_64:
        size:
        name: Fuse IDE (Windows 64bit)
      ide-linux:
        size:
        name: Fuse IDE (Linux 32bit)
      ide-linux_64:
        size:
        name: Fuse IDE (Linux 64bit)


