name: Red Hat JBoss Data Grid 
abbreviated_name: JBoss Data Grid
forum_url: https://community.jboss.org/en/datagrid
current_version: 6.2.0.GA
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
  Developer_Guide:
  Getting_Started_Guide:
  Infinispan_Query_Guide:

