name: Red Hat JBoss Data Grid 
abbreviated_name: JBoss Data Grid
documentation_url: https://access.redhat.com/site/documentation/Red_Hat_JBoss_Data_Grid/
forum_url: https://community.jboss.org/en/datagrid

