name: Red Hat JBoss BRMS
abbreviated_name: JBoss BMRS
tagline: Business Process and Decision Management
has_installer: false
guides: 
  Business_Resource_Planner_Guide:
  Getting_Started_Guide:
  Release_Notes:
  User_Guide:

