name: Red Hat JBoss BRMS
abbreviated_name: JBoss BMRS
tagline: Business Process and Decision Management
has_installer: false
current_version: 6.0.0.Beta
documentation_minor_version: 6-Beta
guides: 
  Business_Resource_Planner_Guide:
  Getting_Started_Guide:
  Release_Notes:
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BRMS/6-Beta/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BRMS/6-Beta/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BRMS/6-Beta/pdf/Release_Notes/Red_Hat_JBoss_BRMS-6-Beta-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BRMS/6-Beta/epub/Release_Notes/Red_Hat_JBoss_BRMS-6-Beta-Release_Notes-en-US.epub
  User_Guide:

