name: Red Hat JBoss BRMS
abbreviated_name: JBoss BMRS
tagline: Business Process and Decision Management
has_installer: false
documentation_url: https://access.redhat.com/site/documentation/JBoss_Enterprise_BRMS_Platform/
