name: Red Hat JBoss BRMS
abbreviated_name: JBoss BMRS
tagline: Business Process and Decision Management
has_installer: false
current_version: 6.0.0.Beta
documentation_minor_version: 6-Beta
guides: 
  Business_Resource_Planner_Guide:
  Getting_Started_Guide:
  Release_Notes:
  User_Guide:

