version: '2'
services:
  awestruct_unit_tests:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    environment:
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL
      - RHD_DRIVER

  awestruct_acceptance_test:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    links:
      - selhub:hub
    environment:
      - ghprbActualCommit
      - github_status_api_token
      - PARALLEL_TEST
      - CUCUMBER_TAGS
      - SELENIUM_HOST=http://hub:4444/wd/hub
      - RHD_JS_DRIVER
      - RHD_DOCKER_DRIVER
      - BUILD_URL

  awestruct:
    build: ../../awestruct
    command:
      - "rake git_setup clean preview[docker]"
    links:
      - searchisko
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - ACCESSIBLE_SLAVE_IP
      - SEARCHISKO_HOST_PORT
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL
      - AWE_PROC_COUNT=10

  mysql:
    build: ../../mysql
    volumes:
      - ../../mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=searchisko
      - MYSQL_USER=searchisko
      - MYSQL_PASSWORD=searchisko
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"

  searchisko:
    build: ../../searchisko
    expose:
     - "8080"
    ports:
     - "8080"
    environment:
      - DB_NAME=searchisko
      - DB_USER=searchisko
      - DB_PASSWORD=searchisko
    links:
     - mysql

  selhub:
    image: selenium/hub
    restart: always
    expose:
      - "4444"
    ports:
      - "4444"
    privileged: true
    environment:
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000

  docker_chrome:
    image: selenium/node-chrome
    volumes:
    - /dev/shm:/dev/shm
    links:
     - selhub:hub
    environment:
     - HUB_PORT_4444_TCP_ADDR=selhub
     - DBUS_SESSION_BUS_ADDRESS=/dev/null