name: DevOps
sub_title: Lorem ipsum dolor sit amet
long_description: Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation
icon: icon-rh-icon-cloud-admin
related_solutions:
  - docker
  - unifiedpush
buzz_tags:
  - DevOps
